version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    depends_on:
      - socket

  socket:
    build:
      context: .
      dockerfile: Dockerfile.socket
    ports:
      - "5001:5001"
    depends_on:
      - mongo

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
